### ISSUE TITLE
Project with child project in subfolders fails

### ISSUE THREAD

**Issue by aodennison** [kuanysh-nabiyev/RenameProjectVsExtension#25]
With
parent
    child

renaming parent project fails.

Removing child project first succeeds.

---------------------------
Microsoft Visual Studio
---------------------------
Close all folders, text editors related to the project

Could not find a part of the path 'C:\Dropbox\2018\Intronis\BlueSky-5.7.x-QaAutomation\QaAutomation\Firebird\AOD.FirebirdHelpersNew\FireBirdHelpers.UnitTests\FireBirdHelpers.UnitTests.csproj'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)

   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)

   at System.IO.File.ReadAllText(String path)

   at Core.ProjectRenamer.RenameInProjectReferences()

   at Core.ProjectRenamer.FullRename()

   at RenameProjectVs2015Extension.RenameCommand.MenuItemCallback(Object sender, EventArgs e) in D:\Downloads\RenameProjectVsExtension-master\RenameProjectVsExtension-master\src\RenameProjectVs2015Extension\RenameProjectVs2015Extension\RenameCommand.cs:line 144
---------------------------
OK   
---------------------------

**Comment by kuanysh-nabiyev** [comment]
The extension tries to find references to selected(renamed) project in other solution projects and to rename it. But cannot to find FireBirdHelpers.UnitTests.csproj file.
@aodennison Is it correct path to FireBirdHelpers.UnitTests project?
C:\Dropbox\2018\Intronis\BlueSky-5.7.x-QaAutomation\QaAutomation\Firebird\AOD.FirebirdHelpersNew\FireBirdHelpers.UnitTests\FireBirdHelpers.UnitTests.csproj

**Comment by aodennison** [comment]
Apologies, Looks like my error, but a formatted error message, instead of a stack trace would be clearer.
Thanks for replying.
